export type NavItem = { path: string; label: string; module: string; badge?: string
  /** Hanya tampil untuk pemilik aplikasi (platform admin). */
  platform?: boolean
  /** Hanya tampil untuk Super Admin tenant. */
  superOnly?: boolean }
export type NavGroup = { key: string; label: string; icon: string; unit: string; items: NavItem[] }

/** Struktur menu Panel Admin NUSAKARYA.
 *  `module` dipakai untuk penyaringan hak akses (role_module_access). */
export const NAV: NavGroup[] = [
  { key: 'exec', label: 'Eksekutif', icon: 'LayoutDashboard', unit: 'EXECUTIVE', items: [
    { path: '/dashboard', label: 'Ringkasan Perusahaan', module: 'DASHBOARD' },
    { path: '/eksekutif', label: 'Portal Eksekutif', module: 'EXECUTIVE' },
    { path: '/inbox', label: 'Inbox Kerja', module: 'CORE' },
    { path: '/persetujuan', label: 'Inbox Persetujuan', module: 'DASHBOARD' },
    { path: '/notifikasi', label: 'Notifikasi', module: 'DASHBOARD' },
  ]},
  { key: 'hr', label: 'Human Resource', icon: 'Users', unit: 'HR', items: [
    { path: '/hr/dashboard', label: 'Dashboard HR', module: 'HR' },
    { path: '/hr/karyawan', label: 'Data Karyawan', module: 'HR' },
    { path: '/hr/formasi', label: 'Formasi & Jabatan', module: 'HR' },
    { path: '/hr/sertifikasi', label: 'Kontrak & Sertifikasi', module: 'HR' },
    { path: '/hr/absensi', label: 'Absensi Lapangan', module: 'HR' },
    { path: '/hr/roster', label: 'Roster & Shift', module: 'HR' },
    { path: '/hr/cuti', label: 'Cuti & Izin', module: 'HR' },
    { path: '/hr/komponen-gaji', label: 'Komponen Gaji', module: 'PAYROLL' },
    { path: '/hr/setelan-bpjs', label: 'Setelan BPJS & Pajak', module: 'PAYROLL' },
    { path: '/hr/payroll', label: 'Payroll & Slip Gaji', module: 'PAYROLL' },
    { path: '/hr/produktivitas', label: 'Produktivitas Teknisi', module: 'PRODUCTIVITY' },
    { path: '/hr/freelance', label: 'Mitra Freelance & Rate Card', module: 'PAYROLL' },
    { path: '/hr/payroll-freelance', label: 'Payout Mitra Freelance', module: 'PAYROLL' },
    { path: '/hr/lembur', label: 'Pengajuan Lembur (SPL)', module: 'HR' },
    { path: '/hr/perjalanan', label: 'Dinas & Reimbursement', module: 'HR' },
    { path: '/hr/kasbon', label: 'Kasbon Karyawan', module: 'HR' },
    { path: '/hr/rekrutmen', label: 'Rekrutmen', module: 'HR' },
    { path: '/hr/kompetensi', label: 'Kompetensi & Pelatihan', module: 'HR' },
    { path: '/hr/penilaian', label: 'Penilaian Kinerja', module: 'HR' },
    { path: '/hr/disiplin', label: 'Tindakan Disiplin', module: 'HR' },
  ]},
  { key: 'commerce', label: 'Commerce', icon: 'Handshake', unit: 'COMMERCE', items: [
    { path: '/commerce/dashboard', label: 'Dashboard Commerce', module: 'COMMERCE' },
    { path: '/commerce/pelanggan', label: 'Pelanggan & Principal', module: 'COMMERCE' },
    { path: '/commerce/kontrak', label: 'Kontrak', module: 'COMMERCE' },
    { path: '/commerce/price-list', label: 'Price List Kontrak', module: 'COMMERCE' },
    { path: '/commerce/spk', label: 'SPK', module: 'COMMERCE' },
    { path: '/commerce/klaim', label: 'Klaim Progres / BA', module: 'COMMERCE' },
    { path: '/commerce/bast', label: 'BAST', module: 'COMMERCE' },
    { path: '/commerce/invoice', label: 'Invoice Pelanggan (AR)', module: 'COMMERCE' },
    { path: '/commerce/penalti', label: 'Penalti SLA', module: 'COMMERCE' },
    { path: '/commerce/pipeline', label: 'Pipeline Tender & Peluang', module: 'COMMERCE' },
    { path: '/commerce/komplain', label: 'Komplain & CSAT', module: 'COMMERCE' },
  ]},
  { key: 'procurement', label: 'Procurement', icon: 'ShoppingCart', unit: 'PROCUREMENT', items: [
    { path: '/procurement/dashboard', label: 'Dashboard Procurement', module: 'PROCUREMENT' },
    { path: '/procurement/vendor', label: 'Vendor', module: 'PROCUREMENT' },
    { path: '/procurement/katalog', label: 'Katalog Item', module: 'PROCUREMENT' },
    { path: '/procurement/pr', label: 'Purchase Request', module: 'PROCUREMENT' },
    { path: '/procurement/rfq', label: 'RFQ & Penawaran', module: 'PROCUREMENT' },
    { path: '/procurement/po', label: 'Purchase Order', module: 'PROCUREMENT' },
    { path: '/procurement/gr', label: 'Good Receive', module: 'PROCUREMENT' },
    { path: '/procurement/invoice-vendor', label: 'Invoice Vendor (3-way)', module: 'PROCUREMENT' },
    { path: '/procurement/scorecard', label: 'Vendor Scorecard', module: 'PROCUREMENT' },
    { path: '/procurement/kontrak-vendor', label: 'Kontrak Rangka Vendor', module: 'PROCUREMENT' },
    { path: '/procurement/retur', label: 'Retur ke Vendor (RTV)', module: 'PROCUREMENT' },
  ]},
  { key: 'finance', label: 'Finance', icon: 'Wallet', unit: 'FINANCE', items: [
    { path: '/finance/dashboard', label: 'Dashboard Finance', module: 'FINANCE' },
    { path: '/finance/ap', label: 'Hutang & Bayar Mitra (AP)', module: 'FINANCE' },
    { path: '/finance/ar', label: 'Piutang (AR)', module: 'FINANCE' },
    { path: '/finance/job-costing', label: 'Job Costing & Margin', module: 'FINANCE' },
    { path: '/finance/anggaran', label: 'Anggaran', module: 'FINANCE' },
    { path: '/finance/cashflow', label: 'Arus Kas', module: 'FINANCE' },
    { path: '/finance/coa', label: 'Bagan Akun (COA)', module: 'FINANCE' },
    { path: '/finance/jurnal', label: 'Jurnal Umum', module: 'FINANCE' },
    { path: '/finance/pajak', label: 'Pusat Pajak', module: 'FINANCE' },
    { path: '/finance/kas-kecil', label: 'Kas Kecil', module: 'FINANCE' },
    { path: '/finance/bank', label: 'Bank & Rekonsiliasi', module: 'FINANCE' },
    { path: '/finance/referensi-pajak', label: 'Referensi Tarif Pajak', module: 'FINANCE' },
  ]},
  { key: 'inventory', label: 'Inventory', icon: 'Boxes', unit: 'INVENTORY', items: [
    { path: '/inventory/dashboard', label: 'Dashboard Inventory', module: 'INVENTORY' },
    { path: '/inventory/gudang', label: 'Gudang', module: 'INVENTORY' },
    { path: '/inventory/stok', label: 'Saldo Stok', module: 'INVENTORY' },
    { path: '/inventory/nte', label: 'Inventory NTE (Serial)', module: 'INVENTORY' },
    { path: '/inventory/mutasi', label: 'Mutasi Stok', module: 'INVENTORY' },
    { path: '/inventory/permintaan', label: 'Permintaan Material', module: 'INVENTORY' },
    { path: '/inventory/pemakaian', label: 'Pemakaian vs BoQ', module: 'INVENTORY' },
    { path: '/inventory/opname', label: 'Stock Opname', module: 'INVENTORY' },
  ]},
  { key: 'asset', label: 'Inventory Aset', icon: 'Truck', unit: 'INVENTORY', items: [
    { path: '/aset/daftar', label: 'Daftar Aset', module: 'ASSET' },
    { path: '/aset/penugasan', label: 'Penugasan Aset', module: 'ASSET' },
    { path: '/aset/pemeliharaan', label: 'Pemeliharaan Aset', module: 'ASSET' },
  ]},
  { key: 'ops', label: 'Operations', icon: 'Wrench', unit: 'OPERATIONS', items: [
    { path: '/ops/dashboard', label: 'Dashboard Operations', module: 'OPERATIONS' },
    { path: '/ops/tiket', label: 'Tiket Gangguan', module: 'OPERATIONS' },
    { path: '/ops/dispatch', label: 'Papan Dispatch', module: 'OPERATIONS' },
    { path: '/ops/work-order', label: 'Work Order', module: 'OPERATIONS' },
    { path: '/ops/maintenance', label: 'Maintenance & Patroli', module: 'OPERATIONS' },
    { path: '/ops/aset-jaringan', label: 'Aset Jaringan', module: 'OPERATIONS' },
    { path: '/ops/rca', label: 'RCA 4 Aspek', module: 'OPERATIONS' },
    { path: '/ops/alarm', label: 'Alarm NMS', module: 'OPERATIONS' },
    { path: '/ops/sla-pelanggan', label: 'Laporan SLA Pelanggan', module: 'OPERATIONS' },
    { path: '/ops/eskalasi', label: 'Matriks Eskalasi', module: 'OPERATIONS' },
    { path: '/ops/pengetahuan', label: 'Basis Pengetahuan', module: 'OPERATIONS' },
    { path: '/ops/morning', label: 'MORNING — Provisioning', module: 'OPERATIONS' },
    { path: '/ops/bmon', label: 'BMON — Assurance', module: 'OPERATIONS' },
  ]},
  { key: 'k3', label: 'K3 / HSE', icon: 'HardHat', unit: 'OPERATIONS', items: [
    { path: '/k3/dashboard', label: 'Dashboard K3', module: 'OPERATIONS' },
    { path: '/k3/insiden', label: 'Laporan Insiden', module: 'OPERATIONS' },
    { path: '/k3/inspeksi', label: 'Inspeksi APD & Alat', module: 'OPERATIONS' },
    { path: '/k3/izin-kerja', label: 'Izin Kerja (Work Permit)', module: 'OPERATIONS' },
  ]},
  { key: 'deploy', label: 'Design & Deployment', icon: 'Map', unit: 'DEPLOYMENT', items: [
    { path: '/deploy/dashboard', label: 'Dashboard Deployment', module: 'DEPLOYMENT' },
    { path: '/deploy/proyek', label: 'Proyek', module: 'DEPLOYMENT' },
    { path: '/deploy/survey', label: 'Survey', module: 'DEPLOYMENT' },
    { path: '/deploy/drm', label: 'DRM', module: 'DEPLOYMENT' },
    { path: '/deploy/boq', label: 'BoQ Plan vs Actual', module: 'DEPLOYMENT' },
    { path: '/deploy/progres', label: 'Progres & Kurva S', module: 'DEPLOYMENT' },
    { path: '/deploy/qc', label: 'Quality Control', module: 'DEPLOYMENT' },
    { path: '/deploy/dokumen', label: 'Dokumen & ABD', module: 'DEPLOYMENT' },
    { path: '/deploy/rfs', label: 'BAST & RFS', module: 'DEPLOYMENT' },
    { path: '/deploy/perizinan', label: 'Perizinan & RoW', module: 'DEPLOYMENT' },
    { path: '/deploy/punchlist', label: 'Punch List & Defect', module: 'DEPLOYMENT' },
    { path: '/deploy/garansi', label: 'Masa Garansi', module: 'DEPLOYMENT' },
    { path: '/deploy/subkon', label: 'Paket Subkontraktor', module: 'DEPLOYMENT' },
  ]},
  { key: 'workspace', label: 'Workspace', icon: 'Rocket', unit: 'CORE', items: [
    { path: '/onboarding', label: 'Siapkan Workspace', module: 'CORE', superOnly: true },
    { path: '/pengaturan/langganan', label: 'Paket & Pemakaian', module: 'CORE' },
    { path: '/pengaturan/undang', label: 'Undang Tim', module: 'CORE' },
    { path: '/pengaturan/field-kustom', label: 'Field Kustom', module: 'CORE' },
    { path: '/pengaturan/alur-kerja', label: 'Status, SLA & Alur', module: 'CORE' },
    { path: '/pengaturan/tabel-kustom', label: 'Tabel Kustom', module: 'CORE' },
    { path: '/pengaturan/preferensi', label: 'Pengaturan Perusahaan', module: 'CORE' },
    { path: '/pengaturan/ekspor', label: 'Ekspor & Cadangan', module: 'CORE' },
    { path: '/platform', label: 'Panel Pemilik Aplikasi', module: 'CORE', platform: true },
  ]},
  { key: 'setting', label: 'Pengaturan', icon: 'Settings', unit: 'CORE', items: [
    { path: '/pengaturan/pengguna', label: 'Pengguna', module: 'CORE' },
    { path: '/pengaturan/hak-akses', label: 'Hak Akses Jabatan', module: 'CORE' },
    { path: '/pengaturan/cabang', label: 'Cabang', module: 'CORE' },
    { path: '/pengaturan/perusahaan', label: 'Profil Perusahaan', module: 'CORE' },
    { path: '/pengaturan/tampilan', label: 'Tampilan & Template', module: 'CORE' },
    { path: '/pengaturan/master', label: 'Data Master Referensi', module: 'CORE' },
    { path: '/pengaturan/impor', label: 'Impor Data', module: 'CORE' },
    { path: '/pengaturan/kesiapan', label: 'Kesiapan Produksi', module: 'CORE' },
    { path: '/pengaturan/audit', label: 'Log Audit', module: 'CORE' },
  ]},
]

export const ALL_ITEMS: (NavItem & { group: string })[] =
  NAV.flatMap(g => g.items.map(i => ({ ...i, group: g.label })))
